spring:
  cloud:
    openservicebroker:
      api-version: 2.13
      api-version-check-enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: user
    password: ~
  liquibase:
    enabled: true

    change-log: classpath:database-changelog.sql
logging:
  level:
    ru.test.load: debug
  file: load_broker.log
